[package]
name = "tf-unused"
version = "1.201909.7"
authors = ["Semyon Novikov <nsa@bedlam.io>"]
edition = "2018"

[profile.release]
debug = false
lto = true

[dependencies]
regex = "1"
glob = "0.3"
clap = "2"
lazy_static = "1"
itertools = "0.8"